[package]
name = "list-images"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.59"
base64 = "0.13.0"
image = "0.24.3"
nix = { version = "0.24.2", default-features = false, features = ["term", "fs"] }
turbojpeg = { version = "0.5.0", features = ["image"] }

[profile.release]
lto = true
