[package]
name = "list-images"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
image = "0.24.3"
turbojpeg = { version = "0.5.0", features = ["image"] }

[profile.release]
lto = true
